### ISSUE TITLE
Mashing F5 crashes Brackets

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#10779]
Found this small issue that most won't run into when testing out for #10769 but anyway:

(Windows 8.1., Brackets 1.2.)
1. Open Brackets
2. Repeatedly reload the project with `F5`
3. Soon-ish Brackets hangs and can only be terminated via Task Manager: 

![image](https://cloud.githubusercontent.com/assets/7641760/6769358/adf4d2ce-d0a0-11e4-9d22-7fdbee6cc66a.png)

**Comment by prksingh** [comment]
Am able to reproduce on Windows 7 as well. Thanks for reporting. Adding 'move to backlog' so we can assign some priority to this. Looks like a very rare scenario so may not be an urgent fix.

**Comment by ryanstewart** [comment]
Marking low priority.

**Comment by petetnt** [comment]
Just noticed when trying out #10906 that holding down F5 will crash Brackets within seconds

**Comment by sagiegurari** [comment]
Why is this one low priority? When you install an extension it results in reload and can freeze brackets.
The only way out is to kill the brackets process.
After 6 months with this issue, I'm not sure that anyone is looking at this.

**Comment by abose** [comment]
This has been fixed in 1.5. Please update to latest version :+1:

**Comment by abose** [comment]
Feel free to reopen this issue if you find this in the latest version.

**Comment by sagiegurari** [comment]
I saw the setTimeout workaround, but I still reproduced it with 1.5
Are you 100% sure this doesn't happen to others with 1.5?

**Comment by petetnt** [comment]
I am almost sure (I haven't installed the newest build yet that ships with different `shell` I have on now...) that this particular bug is similar, but not fixed by #11505. Smashing F5 still crashes Brackets for good: easiest way to reproduce this is by holding F5 while Brackets is active.

**Comment by petetnt** [comment]
Confirmed against latest master with the newest shell: The #11505 helps but does not completely fix this issue.

**Comment by abose** [comment]
Does this happen when you press f5 and then while brackets is reloading, press f5 again- that is causing a crash in my machine. But simply pressing f5 and waiting for the reload to complete does not cause the crash.

**Comment by abose** [comment]
Maybe a fix would be to hold off reloading till brackets app ready is done?

**Comment by sagiegurari** [comment]
Yes exactly

**Comment by petetnt** [comment]
@abose I think yes. Currently holding down `F5` constantly reloads the page (it's Chromium behaviour), so debouncing the reload event could help too.
