### ISSUE TITLE
Live Preview Error - Not detecting index.html files or html files with different name

### ISSUE THREAD

**Issue by sedhuait** [adobe/brackets#11519]
On Working with index.html
![image](https://cloud.githubusercontent.com/assets/1628931/9002131/cb18e090-377d-11e5-8d0b-8d40102874ec.png)

On Working with opened .html files with different name. 

![image](https://cloud.githubusercontent.com/assets/1628931/9002168/3645d2f6-377e-11e5-9e29-a32f3d5c1454.png)

Console Log : 
```
Download the React DevTools for a better development experience: http://fb.me/react-devtools
/utils/DeprecationWarning.js:90 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:548:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start

```

My System is running on Win 7 64 Bit
With Brackets Version : Release 1.4 build 1.4.0-16380 (release 273804eb3)

**Comment by sedhuait** [comment]
After trying few times, it throws  Max connection attempts reached

```

/thirdparty/react.js:4486 Download the React DevTools for a better development experience: http://fb.me/react-devtools
/utils/DeprecationWarning.js:90 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:548:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/filesystem/FileSystem.js:896 Failed to watch root:  C:/Project/Web/ Max connection attempts reached
/project/ProjectManager.js:751 Error watching project root:  C:/Project/Web/ Max connection attempts reached
70/utils/NodeConnection.js:89 WebSocket connection to 'ws://localhost:50297/' failed: WebSocket opening handshake timed out
/project/ProjectManager.js:776 Error unwatching project root:  C:/Project/Web/ RootNotBeingWatched


```

**Comment by sedhuait** [comment]
Health Report : 
```
{
    "uuid": "d2fddec3-fbf7-4201-a03c-151f25246cf0",
    "snapshotTime": 1438328283595,
    "os": "win",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.4.0.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "en-US",
    "bracketsLanguage": "en-US",
    "bracketsVersion": "1.4.0-16380",
    "fileStats": {
        "openedFileExt": {
            "html": 3,
            "css": 1
        },
        "workingSetFileExt": {
            "html": 1
        }
    },
    "projectLoadTimes": ":81:5(25)45[20]",
    "fileOpenTimes": ":139",
    "ModuleDepsResolved": 607,
    "AppStartupTime": 1418,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [],
    "bracketsTheme": "light-theme"
}
```

**Comment by abose** [comment]
If you are in win 8.1 or later try this>
Cloase brackets,
Open task manager> kill process Evented I/O for v8 JavaScript (node.exe)
Relaunch brackets.

**Comment by sedhuait** [comment]
@abose : Sorry I'm using  Win 7 Professional

**Comment by abose** [comment]
Its the same
It looks like the node process is not respnding.
If you are in win 7 try this>
Cloase brackets,
Open task manager> node.exe or brackets node.exe
Relaunch brackets.

**Comment by sedhuait** [comment]
@abose : Sorry Arun. There is no task in that name

**Comment by abose** [comment]
Or try 
File menu> enable experimental live view.

**Comment by sedhuait** [comment]
hey, i found something. When I checked in other machine ( which has Brackets 1.3 ) , there is node 32 process is getting started when running Brackets. But in my machine, that node 32 process is missing. 

I think it is the cause for it.

**Comment by sedhuait** [comment]
and menu> enable experimental live view is enabled.

**Comment by sedhuait** [comment]
@abose and when i tried to restart node -- > Debug Menu - Restart Node, got the following error 

![image](https://cloud.githubusercontent.com/assets/1628931/9005794/e6243de6-379e-11e5-8423-8c993d2a99a4.png)

**Comment by abose** [comment]
also try deleting the brackets folder at %appdata%/brackets [this will reset brackets] . If that dosen't fix it, try reinstalling brackets, and restart windows, that might fix it. The reason is that brackets -node process is not present in the machine.

**Comment by sedhuait** [comment]
I tried this before, it works for a the first time ( few times only not all the times )  and then it fails !! Back to the same stage.

**Comment by abose** [comment]
for the time being try disabling menu> enable experimental live view 
Will need to see why this happens.

**Comment by sedhuait** [comment]
Sorry @abose : that didnt help. when "experimental live view " is disabled, it opens a new chrome window then it stops. 

![image](https://cloud.githubusercontent.com/assets/1628931/9007972/23d5ae3a-37b4-11e5-8e8a-60e294272cd7.png)

and brackets says : 

![image](https://cloud.githubusercontent.com/assets/1628931/9007977/383687a0-37b4-11e5-85c9-8e27b968d887.png)


Console Log : 

![image](https://cloud.githubusercontent.com/assets/1628931/9007991/57efc836-37b4-11e5-922c-f32d70f41595.png)

**Comment by abose** [comment]
open debug>preferences> and add "findInFiles.nodeSearch": false,
restart the system.

**Comment by sedhuait** [comment]
@abose  : its doesn't help.

**Comment by abose** [comment]
All the error shown in the console seems to be brackets not able to contact with chrome remote debugging port. Our old live dev workflow required chrome with RDP. But the new experimental live view should not have the problem.
file> Enable Experimental live view->make sure that the option is ticked, restart the machine, and if there is an error in the dev console, please paste it here.

**Comment by MarcelGerber** [comment]
@abose As he already stated above, he had "Experimental Live Preview" enabled before, and it didn't work either.

Also, as he found at that Node is not running, that's the cause - not something wrong with Chrome's RDP or similar.

**Comment by sedhuait** [comment]
@abose : No error in the console and also live preview is not working as well.  Please find the logs below. 

 ```
Download the React DevTools for a better development experience: http://fb.me/react-devtools
/utils/DeprecationWarning.js:90 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:548:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start


Error watching project root:  C:/xxxxx/yyyyyyy/ Max connection attempts reached

```

**Comment by HanSolo0001** [comment]
@sedhuait Do you have Teamviewer so I can take a  look at the files Brackets is using? Teamviewer is  free software that lets you or someone else remotely connect to your computer or another computer. Sometimes people (like me) need to physically see what's happening in order to further help with the issue. I would like to see it, since you and @abose have already gone over lots of console logs, screenshots, and etc.

**Comment by sedhuait** [comment]
@HanSolo0001 :Yes I have. When are you available? It can be today (6 hrs left)  or Monday.

**Comment by HanSolo0001** [comment]
Hey @sedhuraja are you available this Sunday say about 8:00pm EST?

On Friday, August 7, 2015, sedhuraja <notifications@github.com> wrote:

> @HanSolo0001 <https://github.com/HanSolo0001> :Yes I have. When are you
> available? It can be today (6 hrs left) or Monday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/11519#issuecomment-128607348>.
>


-- 
Thanks,
 Daniel

**Comment by sedhuait** [comment]
@HanSolo0001 : Hey this issue happens only in my work system. So I can give you access only during my office hours. 11AM - 7PM IST.

**Comment by HanSolo0001** [comment]
Hey if it's only in your work system, then it could be your work's Internet
blocking it through their firewall. Have you tried getting in touch with
your IT guys there first?

On Tue, Aug 11, 2015 at 1:37 AM, sedhuraja <notifications@github.com> wrote:

> @HanSolo0001 <https://github.com/HanSolo0001> : Hey this issue happens
> only in my work system. So I can give you access only during my office
> hours. 11AM - 7PM IST.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/11519#issuecomment-129711228>.
>



-- 
Thanks,
 Daniel

**Comment by sedhuait** [comment]
@HanSolo0001 : But it works in my colleague's machine. How about Team viewer access now ?

**Comment by HanSolo0001** [comment]
That's interesting. Well sorry I missed you. Let me see if I can get some
screenshot's of my Brackets and send it to you, and if you have all the
files then we'll go from there and try to set up a date and all for
Teamviewer. I'm off work tomorrow (8/12/15 Wednesday). I'm in the Eastern
Standard Time zone (EST).

On Tue, Aug 11, 2015 at 3:56 AM, sedhuraja <notifications@github.com> wrote:

> @HanSolo0001 <https://github.com/HanSolo0001> : But it works in my
> colleague's machine. How about Team viewer access now ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/11519#issuecomment-129748464>.
>



-- 
Thanks,
 Daniel

**Comment by HanSolo0001** [comment]
Ok was going to get some screenshots, but there would be way too many. So
let's just try and set up a time and date where we can Teamviewer, and
hopefully I might be able to help you out.

On Tue, Aug 11, 2015 at 11:07 PM, Daniel Hildreth <pillarite@gmail.com>
wrote:

> That's interesting. Well sorry I missed you. Let me see if I can get some
> screenshot's of my Brackets and send it to you, and if you have all the
> files then we'll go from there and try to set up a date and all for
> Teamviewer. I'm off work tomorrow (8/12/15 Wednesday). I'm in the Eastern
> Standard Time zone (EST).
>
> On Tue, Aug 11, 2015 at 3:56 AM, sedhuraja <notifications@github.com>
> wrote:
>
>> @HanSolo0001 <https://github.com/HanSolo0001> : But it works in my
>> colleague's machine. How about Team viewer access now ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/adobe/brackets/issues/11519#issuecomment-129748464>.
>>
>
>
>
> --
> Thanks,
>  Daniel
>



-- 
Thanks,
 Daniel

**Comment by sedhuait** [comment]
@HanSolo0001 : hey how some time on Thursday then? Some time in the early morning of your time (ET). So like 7:00 AM - 9:30 AM ET.

**Comment by HanSolo0001** [comment]
That unfortunately won't work for me. Would next Tuesday (8/18/2015) or
Wednesday (8/19/2015) work say around 11am EST?

On Wed, Aug 12, 2015 at 1:06 AM, sedhuraja <notifications@github.com> wrote:

> @HanSolo0001 <https://github.com/HanSolo0001> : hey how some time on
> Thursday then? Some time in the early morning of your time (ET). So like
> 7:00 AM - 9:30 AM ET.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/11519#issuecomment-130167192>.
>



-- 
Thanks,
 Daniel

**Comment by MarcelGerber** [comment]
I just connected to @sedhuait's PC to dive into this issue.
So...:
* The node process is running (it shows up in the task manager and `brackets.app.getNodeState()` doesn't return an error)
* `localhost` is correctly mapped to `127.0.0.1` (and `::1`)
* StaticServer's NodeDomain cannot connect to Node (its `_domainLoaded` is always `false`)

**Comment by HanSolo0001** [comment]
So I did some digging with the Node Domain stuff and found this actually on
GitHub. Maybe it'll help? It also has some debugging issues down at the
bottom of the page.

https://github.com/adobe/brackets/wiki/Brackets-Node-Process:-Overview-for-Developers

On Thu, Aug 13, 2015 at 6:39 AM, Marcel Gerber <notifications@github.com>
wrote:

> I just connected to @sedhuait <https://github.com/sedhuait>'s PC to dive
> into this issue.
> So...:
>
>    - The node process is running (it shows up in the task manager and
>    brackets.app.getNodeState() doesn't return an error)
>    - localhost is correctly mapped to 127.0.0.1 (and ::1)
>    - StaticServer's NodeDomain cannot connect to Node (its _domainLoaded
>    is always false)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/11519#issuecomment-130608645>.
>



-- 
Thanks,
 Daniel

**Comment by TheInitializer** [comment]
I have the same problem. I have the experimental mode enabled and Chrome isn't installed...

**Comment by TheInitializer** [comment]
I clicked "Enable Node Debugger" and "Log Node State to Console and it works now... Odd. :/

**Comment by TheInitializer** [comment]
After restarting Brackets it stopped working. I clicked those two buttons again and it still doesn't work

**Comment by TheInitializer** [comment]
I figured out the problem. I'd marked the html files as Django files because I'd worked with Django before and it was more convenient then. Sorry for the trouble.

@sedhuait do you have your html files marked as anything other than html?

**Comment by sedhuait** [comment]
@TheInitializer yes i was having .jsp files

**Comment by TheInitializer** [comment]
@sedhuait they seem to be marked as html, so you _should_ be fine...

however it seems that you aren't. hm

**Comment by theprash007** [comment]
i had same issue... but got fixed...  i had changed file type to svg instead of html in lower right corner of the window... then same error was coming... i struggled for 5-6 hours...  reinstalled both chrome and brackets several times... :D but then i tried setting that file type to "html" in lower right corner and it worke.... :D

**Comment by SDeamer** [comment]
@sedhuait Did you find out what was wrong? I am having the exact same issue and cannot figure it out. I am new to all of this. Thank you.

**Comment by theprash007** [comment]
![image](https://cloud.githubusercontent.com/assets/14899289/12047973/7f6fa5ee-aefa-11e5-8a55-fa916e9aad19.png)

**Comment by laurencaponong** [comment]
I was having this constant problem with 1.5.  I updated to 1.6 and it was still giving me the same error.  The below steps worked for me:

What I did was:

1. Delete Brackets.app folder in Applications
2. Installed Brackets 1.6 again in Applications folder
3. Opened .HTML file with Brackets 1.6
4. I **did not** have "Enable Experimental Live Preview" checked.  (File > Enable Experimental Live Preview)

After I did this, it worked.  Hope this helps.

**Comment by martijntjuhhh** [comment]
@TheInitializer @SDeamer @sedhuait
 I actually made a github account just to answer this question, 

I've been experiencing the same problem, I reinstalled Brackets, deleted folders and closed node in the task manager etc. What did the job for me eventually, was _making a new folder on my desktop: _**file (top left corner) > open folder > desktop > right mouseclick> new > folder**. Then I changed my html name to "index.html" and it did the job. I restarded Brackets a few times during the progress since sometimes changes don't work unless you restart your program. 

I hope this comment (and account xd) helped anyone out.

**Comment by zmasinelli** [comment]
@martijntjuhhh  This worked for me! Thanks!

**Comment by martijntjuhhh** [comment]
@zsmasinelli You're welcome!

**Comment by sedhuait** [comment]
@TheInitializer @SDeamer : I haven't figured it out. It works after a system restart  or app restart. 
I think Node Evented IO for Javascript is causing it.

**Comment by sedhuait** [comment]
@TheInitializer : It even happens with very basic app with one index.html n main.js project.

**Comment by TheInitializer** [comment]
interesting...

**Comment by JMGoebel** [comment]
Just started having this problem today.  I unchecked 'Enable Experimental Live Preview,' now everything is working as it should be.

**Comment by Yeswanth-JG** [comment]
@sedhuait @HanSolo0001 ...

I had seen few comments mentioning to create a folder in bottom right....  or folder deletion and re-installing...

Now I got the issue after updating the app. Even I have issues with extensions...

Below screenshot of "failed live preview".

![image](https://cloud.githubusercontent.com/assets/5590842/20552364/27c93ade-b170-11e6-9bed-f5d49461ba8a.png)

Below screenshot.. "Not able update an extension (even nt able 2 remove)"

![image](https://cloud.githubusercontent.com/assets/5590842/20552397/7044972c-b170-11e6-8af1-c8cb718b61c8.png)

_Extensionn Name_ **[Extension highlighter]**
**System : Win 10 (latest update!)**
****

**Comment by AwesomeBa** [comment]
I have recently seen this problem.
I moved everything required by the html to one folder (css, images, etc...).
Then I 'ran' an image in that project, and it worked!
Running the html still did not work though.

**Comment by Interned** [comment]
- Using Version 1.9 Edition 1.9.0-17312
- Windows 8.1

Hi,

As this issue

> Not detecting index.html files or html files with different name

may happen when I was opening Brackets first and then my folder from` open folder >`, etc., I just tried to  first use the right mouseclick on my folder - wich is on a USB flash drive -  to open it with Brackets.
And... it works, I mean "the Enable Experimental Live Preview" works fine.

**Comment by tintinve** [comment]
I fixed by opening the folder containing the whole project instead of individual files in Brackets. When you have all the folder files loaded within brackets the live preview works.

**Comment by arpit999** [comment]
I found the solution for live preview.
First, **disable** the **enableExpermintalPreview** then select your index file and **enable** the **Live Preview**.

**Comment by uniqorn2009** [comment]
I was having this same issue but one thing I did notice that I was working in the Getting Started folder event though I was saving to a different one. It wasn't until I read "martijntjuhhh commented on Feb 1, 2016"
They mentioned opening file>open folder> click on New Folder and giving it a name. Then save your index.html there. It should open now in experimental preview

**Comment by baerus** [comment]
uniqorn2009: Perfect, that helped!
Although my index.html was selected in brackets, the selected folder seemed to be my "css" folder. Choosing "open folder", selecting the root folder, then selecting the index.html again, did the trick. Now the experimental live preview seem to work :)

**Comment by marakmuna** [comment]
Im in linux parrot sec as a root user 
Brackets does'nt even launch ,
Tried removing noroot from brackets.profile still not launching
Need help thank you

**Comment by renegaders** [comment]
> I am facing the same problem in **Brackets 1.11**. I found the solution for live preview.
> First, **disable** the **enableExpermintalPreview** then select your index file and **enable** the **Live Preview**.
> 
> See below screenshot
> ![untitled](https://user-images.githubusercontent.com/13213925/31908607-7a60e782-b805-11e7-856a-939238c74d0d.png)

Tried that, and many other things in the latest version 1.13 and it always failed. A few times I though I figured it out until, after a few days later, same problem popped up again. Then it was something else, Next time something else again. It's like chasing the geese.

**Comment by renegaders** [comment]
> Im in linux parrot sec as a root user
> Brackets does'nt even launch ,
> Tried removing noroot from brackets.profile still not launching
> Need help thank you

That's another reason why I totally quit on Brackets. There is no assistance available at all. You ask for help when, April? It's mid September now. If you don't wanna wait another 2 years, I suggest you get yourself an IDE that works, for a start, ad if you run into problems, least you get help. I don't know about the others, but I don't have time waiting for eternity to find a solution. :)

**Comment by altiseven** [comment]
Just go to File Menu, Open Folder and then select the .html file and preview it.

**Comment by javist94** [comment]
I solved this issue just by **running Brackets as Administrator**... (with the experimental preview enabled)
Right click on Brackets icon -> Run as Administrator -> Yes
Sorted out

**Comment by renatoschroepfer** [comment]
I had the same problem. However I realized that the error happened soon after installing extensions, for some reason the extensions generated this error. Then I removed the last extensions installed before the problem and everything was solved. ---> And do not forget to restart your Brackets Editor after removing the extensions.

**Comment by theol0403** [comment]
I had this issue, when enabling "Experimental Live Preview". 
I solved it by spamming `Debug->Restart Node`, `Debug->Enable Node Debugger`, and `Debug->Log Node State to Console`. 
After that, pressing "Live Preview" would do nothing. 
Then, after restarting Brackets, the issue was solved.

**Comment by mjkode** [comment]
Thanks theol0403, .... followed your steps and it solve my problem too.

"I had this issue, when enabling "Experimental Live Preview".I solved it by spamming Debug->Restart Node, Debug->Enable Node Debugger, and Debug->Log Node State to Console.After that, pressing "Live Preview" would do nothing.Then, after restarting Brackets, the issue was solved."

**Comment by blind0x** [comment]
For everyone, this problem can be resolved by following steps:- 

1. On menu bar, go to  File --> Open Folder (folder which have your html file for live preview)

2. Select Folder

3. Select your html file from left side bar for live preview

4. Click on bolt icon on right (preview button) 

All it melts down to the fact, that you need that folder(which have your file) selected to view your output in live preview. 
Let me know, if it helps someone. :)
![2](https://user-images.githubusercontent.com/16700931/83773066-b4b61a00-a6a1-11ea-8207-2483d9852f62.JPG)
![3](https://user-images.githubusercontent.com/16700931/83773071-b67fdd80-a6a1-11ea-991b-d9d3094d39a5.JPG)
![4](https://user-images.githubusercontent.com/16700931/83773074-b67fdd80-a6a1-11ea-9971-a0b692ed6b98.JPG)
![5](https://user-images.githubusercontent.com/16700931/83773076-b7187400-a6a1-11ea-8fac-269a65ca9d92.JPG)

**Comment by renegaders** [comment]
All it melts down to the fact, that you need that folder(which have your
file) selected to view your output in live preview.
That's what I Always have. It might be "required" in Brackets but really,
it's kinda common sense, Tahid. ;-)
Maybe Brackets has some human trails built in and is moody, doesn't like
certain people, me included, lol.
All it melts down to the fact, that you need that folder(which have your
file) selected to view your output in live preview.

**Comment by renegaders** [comment]
Sahid, sorry.

**Comment by blind0x** [comment]
Brackets have a lot of issues, I have just started using it and have seen a lot of them myself. But hey, we are all developers here, solving these problems is our work. And bro @renegaders sometimes, common sense is not so common, so chill n help your fellows .

**Comment by calvodioni** [comment]
If you have the live preview error, just check  your project settings. And if you have a localhost to display your project, just set it back to default which is blank or remove anything you have in that url box.  I had 127.0.0.1 for localhost and deleted it; it worked fine. Make sure you copy whatever you have in the box in case you have it for specific purposes. Also, if it does not work uninstall and re-install brackets that will also work.

**Comment by calvodioni** [comment]
Brackets is one of the most easiest and stable editor to edit projects

**Comment by calvodioni** [comment]
For live previwe error just open your defaultpreferneces.json file and find line 268, Just remove the word "false" and change it to true that will solve the problem with live view  "livedev.multibrowser": true,
