### ISSUE TITLE
Cannot install any brackets extension

### ISSUE THREAD

**Issue by lkoumis** [adobe/brackets#12064]
I get the error: "Installation failed. Error connecting to the server" for installation for ANY extension.

I am not working behind a proxy and the localhost resolves to the 127.0.0.1

With no extensions, I'd use notepad++.

**Comment by petetnt** [comment]
Make sure that your firewall permits the `Node process` used by Brackets to download the packages.

**Comment by CrNix** [comment]
Hi, I have the same problem but with different error message - Installation failed, Unknown internal error. I just downloaded latest Brackets from git (it says Release 1.8 development build 1.8.0-0 (master 5141df27a)).

Using Linux Mint 17.3 64bit. In some other issue was mentioned that this error was fixed, but still keeps occuring to me. Have to install all extensions by hand - copy the extensions into to extension directory. Even install from URL does not work.

**Comment by petetnt** [comment]
Hi @CrNix,

do you see any errors in the Developer Tools? You can see them in `Debug -> Show Developer Tools`. Check the `console` and `network` after getting that error.

**Comment by CrNix** [comment]
@petetnt Hi, this the message from console: "Unknown installation error extensionManager domain is undefined"

**Comment by descadmx** [comment]
Same as CrNix here. It happened to me while using Debian 8 and Ubuntu. I also deleted all hidden folders in my home directory (such as .config) but still have the same issue.

**Comment by CrNix** [comment]
@petetnt Hi, here is also the line number of the error Package.js:408

**Comment by petetnt** [comment]
Hi @CrNix (and others): could you try the latest `master`. #12702 has a bug fix that most likely won't fix the installation issue, but actually shows more useful information than just `Unknown installation error`

**Comment by CrNix** [comment]
Hi @petetnt, pulled the latest master (commit: master be628813e) but the message in the console is the same.

Here is the GUI dialog shown

![brackets-install-error](https://cloud.githubusercontent.com/assets/15139474/17961469/34770898-6aac-11e6-897a-88ee570eb347.png)

**Comment by stelarossa** [comment]
basicly I have the same problem on windows 8.1 Any suggestions on how to fix this?

**Comment by petetnt** [comment]
@stelarossa is it a 32-bit OS? If it is, download the 32 bit Node.exe from https://nodejs.org/en/download/ and replace the `node.exe` in the Brackets installation folder with it.

**Comment by zaggino** [comment]
Or you can try https://github.com/adobe/brackets/releases/tag/release-1.9-prerelease

**Comment by stelarossa** [comment]
Thank you for your replyes :)
I have tried solutions proposed by you,but it haven't worked...anybody have some other idea?it seems like great editor but without extenssions its not just that good to me(I write a lot of html,so emmet is must have,even tryed downloading it and installing it by simple dragging and it still whan't install it).Hoped to switch to brackets from sublime,but...

**Comment by petetnt** [comment]
@stelarossa Oh, bummer.

Can you check the developers tools if there's any errors after trying to install extensions? You can see the console in `Debug -> Show Developers Tools`. It might be some sort of permission issue if even dragging and dropping fails 🤔

**Comment by zaggino** [comment]
@stelarossa check this guide: https://github.com/zaggino/brackets-npm-registry#how-to-install-brackets-npm-registry

It's written for extension `brackets-npm-registry` but it can be modified to install any extension, for example if I wanted to install `brackets-emmet` from https://github.com/emmetio/brackets-emmet on windows, I'd do this:
```
cd /D %HOMEDRIVE%%HOMEPATH%\AppData\Roaming\Brackets\extensions\user
git clone https://github.com/emmetio/brackets-emmet brackets-emmet
cd brackets-emmet
npm install
```

**Comment by stelarossa** [comment]
/command/Menus.js:831 Error setting menu item shortcut: 1(anonymous function) @ /command/Menus.js:831
thirdparty.min.js:13 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
/command/KeyBindingManager.js:578 Fail to nomalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Fail to nomalize Cmd-Shift-[
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
/filesystem/FileSystem.js:904 Failed to watch root:  C:/Users/stelarossa/Desktop/Simply_A_Circle_New/ Max connection attempts reached
ErrorNotification.js:122 Error watching project root:  C:/Users/stelarossa/Desktop/Simply_A_Circle_New/ Max connection attempts reachedwindow.console.error @ ErrorNotification.js:122
/extensibility/Package.js:414 Unknown installation error extensionManager domain is undefined

my dev tools errors...npm also doesn't work for me,it gives out error Max number of connections reached...any new ideas?

**Comment by zaggino** [comment]
@stelarossa did you test with 1.9? https://github.com/adobe/brackets/releases/tag/release-1.9

**Comment by stelarossa** [comment]
I did the following verifying it won't work:
downloaded 32-bit node.exe and replaced existing one.
downloaded brackets 1.9,deinstalled earlier version,installed new one.
downloaded npm like in tutorial,than tryed downloading emmet like stated above.npm installed successfuly,emmet not,error timeout.
checked firewall rulles just in case,all good...
I'm confused.
Any suggestions,it looks great,but basicly without exstensions it's not that much usefull(just the way I'm useto coding) :)

**Comment by stelarossa** [comment]
ok,it is  installed,finaly.just it won't work...anybody knows what went wrong?same error console

**Comment by stelarossa** [comment]
Basicly I'm uninstalling brackets node with revo uninstaller pro and than will install brackets again.Hope this will work...

**Comment by stelarossa** [comment]
just to let you all know that it didn't work...node is the problem...

Less has finished and no sheets were loaded.
/thirdparty/react.js:6541 Download the React DevTools for a better development experience: https://fb.me/react-devtools
/command/Menus.js:831 Error setting menu item shortcut: 1(anonymous function) @ /command/Menus.js:831
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-[
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "fileWatcher": timeout(anonymous function) @ /utils/NodeDomain.js:144
/filesystem/FileSystem.js:904 Failed to watch root:  C:/Program Files/Brackets/samples/root/Getting Started/ timeout
/project/ProjectManager.js:748 Error watching project root:  C:/Program Files/Brackets/samples/root/Getting Started/ timeout(anonymous function) @ /project/ProjectManager.js:748
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "launcher": timeout(anonymous function) @ /utils/NodeDomain.js:144
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "webSocketTransport": timeout(anonymous function) @ /utils/NodeDomain.js:144
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "FindInFiles": timeout(anonymous function) @ /utils/NodeDomain.js:144
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "nodeSocketTransport": timeout(anonymous function) @ /utils/NodeDomain.js:144
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "staticServer": timeout(anonymous function) @ /utils/NodeDomain.js:144
/extensibility/Package.js:539 [Extensions] Failed to connect to node Arguments[1](anonymous function) @ /extensibility/Package.js:539
/extensibility/Package.js:414 Unknown installation error extensionManager domain is undefined

**Comment by hrvojegolcic** [comment]
Try modifying the extension to use `"view/WorkspaceManager"` instead of `"view/PanelManager"`. I had problem installing the most of the extensions too.
https://github.com/adobe/brackets/issues/11960#issuecomment-374403225

**Comment by NimrahB** [comment]
i cannot install emmet extension.  i have window 8.1

**Comment by skywalker89** [comment]
HI, was close to kicking Brackets off my Win 10 before it had a chance bec of this...use the newest version (1.13) ...what somehow magically worked for me is to deactivate firewall, install my plugin ... no issues
reactivating win firewall ... still works and I can even install other plugins with no prob now...no idea why

not very technical, sorry, hope it helps someone
Dan
