### ISSUE TITLE
Syntax error in live preview. 

### ISSUE THREAD

**Issue by Ulver84** [adobe/brackets#12818]
Hi, 

I get a syntax error in a html file that is very basic/tiny. I have tried to reload Brackets without extensions and cleaned Live Preview Profile/Cache. 

When I first activate live preview it works fine. As you can see in this video, it highlights where my cursor is, I can edit text and everything works fine, however as soon as I edit below the table, even pressing the space bar will produce a syntax error. 

I have a video recording of the issue here 
https://www.youtube.com/watch?v=ZeJV9PvcyiQ

Latest version of Brackets, Chrome, Firefox and Windows 10.

**Comment by ficristo** [comment]
Could you share s minimal snippet of code to reproduce? Thank you.

**Comment by Ulver84** [comment]
Of course :) Link to the folder is here:
https://www.dropbox.com/sh/7z0ce0yzph1vsvk/AABw3vYJUyYNEnd_21Gs-WW1a?dl=0

And a jsfiddle here
https://jsfiddle.net/qgL118ye/

**Comment by petetnt** [comment]
Off topic, but as a cat owner I love that website 😻

**Comment by Ulver84** [comment]
Haha thank you, cats are the best aren't they 😄

**Comment by rbuk** [comment]
Joined GitHub _just_ to say I'm also having this issue! It's heartbreaking, I was beginning to fall in love with Brackets!

**Comment by Ulver84** [comment]
I tried with Brackets 1.8 today, but the problem persists. Is there anything I can do to help troubleshooting?

**Comment by mmcken3** [comment]
I downloaded the drop box code and reproduced the error as well. However, It is interesting because if you save and refresh the live preview it will update and tell you that there are no more syntax errors. But once you start editing again the issue persist. Trying to look into what is causing it now and try to replicate it with my own code. Let me know if there is anything else I could do to help!

**Comment by haslam22** [comment]
I downloaded and fixed the issue by closing the <li> tags in the <nav> element near the top. Anyone else willing to verify?

**Comment by petetnt** [comment]
@haslam22 oh, so this is a duplicate of #7257? It has a PR pending at #12057, which should be reviewed and rebased against master.

**Comment by mmcken3** [comment]
I can verify @haslam22 remarks, looking at all the places I saw the issue, it was the missing optional tags of either li or p.

**Comment by petetnt** [comment]
Working on merging #12057 right now

**Comment by petetnt** [comment]
Fixed in #12057

**Comment by Ulver84** [comment]
Good to hear! =) I saw that the 1.8 pre-release was updated three days ago and was wondering if this fix was included, but I still experience the syntax error, so I guess it hasn't been included yet. I'm completely new to github (and coding in general), and was wondering if there was a way to see when a fix was pushed to a beta or pre-release version? Thank you.

**Comment by petetnt** [comment]
Hi @Ulver84,

due to the branching nature of `git` that is indeed a bit tricky. 

You can try to see if a particular PR is included by

1. Cloning the whole repo `git clone https://github.com/adobe/brackets`
2. Checking out the tagged release `git checkout tags/release-1.8-prerelease`
3. Using `git log --grep='pull/12057/commits'` to see if the particular PR is included (will return nothing if not).

It might not work with squashed/rebased commits though, so one could just see if the changes from the PR are included in the source code.

However, the said fix __should__ be included in the new prerelease. Which is kinda worrying as it doesn't occur for myself anymore 🤔

**Comment by Ulver84** [comment]
I see, a bit more advanced than my current skill level 😄 Thank you still, I'll save those tips for when I become better. 

I just tried to un-install Brackets and re-install the 1.8 pre-release, but I do still experience the issue. 

Version is 
Release 1.8 build 1.8.0-17101 (release 5651f1f26) 
build timestamp: Wed Oct 26 2016 15:19:04 GMT+0100

I'm using the same code posted in the first post. I did notice that both the theme and extensions I installed, were still present after the re-install, so I figured that perhaps Brackets doesn't remove all files and some leftovers cause the bug, but reloading Brackets without extensions doesn't fix it. So a bug in the bug-fix? =)

A side-note, I have closed all the <li> and <p> tags, but that doesn't remove the syntax error for me, so I was wondering if I was missing something.

**Comment by petetnt** [comment]
Thanks for the information @Ulver84, I'll try and come back to this issue ASAP and see if I am able to reproduce it on 1.8 prerelease.

**Comment by Ulver84** [comment]
Uh! I think I'm on to something. I might be a simple PEBKAC error (or error 40 as we call it here). I'll test some more! :)

**Comment by Ulver84** [comment]
My bad, I thought it was a user-error for a second. I noticed that it said "syntax error" immediately, when I typed the < sign and the tag was unfinished, but then it disappeared when I closed the tag. But then I still got a syntax error when I added a <br> further down on the page. I can't see the error and it is W3C validated, so I assume there are no unclosed tags and such, and I can't see anyone myself.

https://www.youtube.com/watch?v=ObyOR0WIaho&feature=youtu.be

**Comment by Ulver84** [comment]
Now I actually think that I worked it out. I noticed in the video, that I was editing in Firefox. I got some live-preview errors in Chrome at one point, while Firefox was working, so I switched. But just now I disabled experimental live-preview and switched to Chrome again, and now the syntax error is gone. I have tested a bit and I can't reproduce the error anymore, so I think that was the culprit.

**Comment by petetnt** [comment]
👍  Great that you got it figured out. Feel free to open a new issue / post in this one if the problem comes back.

**Comment by Ulver84** [comment]
It has come back with a vengeance it seems :( It has happened twice, and after the first syntax error I decided to start from scratch and record my work. I'm doing a tutorial on CSS with html and CSS code provided by the teacher. The html copied from codepen has some white space when copied to Brackets. When I removed it the syntax error occurred. 
https://youtu.be/FidCGSJwN38?t=8m25s

**Comment by Ulver84** [comment]
I figured the error out =) It's because the teacher wrote `<100%>` in the code, instead of (100%). Since there is no `<100%>` tag in HTML, Live Preview stopped working. A bit related: I had a `</div>` tag in my code that had no start tag, and again live preview stopped working, which makes sense. But if I may come with a suggestion, it would be nice if Brackets said something like "are you sure your tags are alright?" or highlighted certain tags that had a missing closing or start tag, or a foreign tag that Brackets couldn't make sense of.
