### ISSUE TITLE
Why wont my css. link to my html it never shows up in the live preview?

### ISSUE THREAD

**Issue by Shawn58** [adobe/brackets#13308]
`<DOCTYPE Html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width+device-width">
<meta name= "description" content="Affordable and Professional web design">
<meta name="keywords" content= " web design, affordable web design, profrofessional web design">
<meta name="author" content="Shawn Crawford">
<title> AcmeWeb Design | Welcome</title>
<link rel="stylesheet" href ="./css/style.css">
</head>
<body>
<header>
<div class="container">
<div id="branding">
<h1>WIVO</h1>
</div>
<NAV>
<V1>
<li class="current"><a href="Home.html">Home</a></li>
<li><a href="Notifications.html">Notifications</a></li>
<li><a href="Profile.html">Profile</a></li>
</V1>
</NAV>
</div>
</header>
<section id="showcase">
<div class="container">
<h1>Affordable Professional Web Design</h1>
<p>Wivo connects with all entertainment</p>
</div>
</section>
<section id="newsletter">
<div class="container">
<h1>subscribe To our Newsletter</h1>
<form>
<input type="email" placeholder="enter Email..."> 
<button type="submit" class="button_1">subscribe</button>
</form>
</div>
<section id="boxes">
<div class="container">
<div class="box">
<img src="Flat-White-and-Orange-Music-Player-Widget-PSD.jpg">
<h3>HTML5 Markup</h3>
<p>Lores ipum dolor sit amet, consectetur adipiscing elit, Vivam</p>
</div>
<div class="box">
<img src="Flat-White-and-Orange-Music-Player-Widget-PSD.jpg">
<h3>css3 styling</h3>
<p>Lores ipum dolor sit amet, consectetur adipiscing elit, Vivam</p>
<div class="box">
<img src="Flat-White-and-Orange-Music-Player-Widget-PSD.jpg">
<h3>Graphic Design</h3>
<p>Lores ipum dolor sit amet, consectetur adipiscing elit, Vivam</p>
</div>
</div>
</section>
<footer>
<p>shawn web design, copyright &copy; 2017</p>
</footer>
</body>
</html>`

**Comment by petetnt** [comment]
Hi @Shawn58,

can you paste the `style.css` file too and show your folder structure?

When opening the Live Preview, can you see any errors in the Developer Tools (Debug -> Show Developer Tools -> Console)?

**Comment by Shawn58** [comment]
body
{font: 15px/1.5 Arial, Helvetica, sans-serif;
padding:0;
margin:0;
background-color: #f4f4f4;
}
/* Global */
.container{
width:80%;
margin: auto;
overflow:hidden;
}
u1{
margin: 0;
padding:0;
}
.button_1{
height:35px;
background:#e8491d;
border:0
padding-left:20px;
padding-right:20px;
color:#ffffff;
}
/* Header **/
header{background:#35424a
color:#ffffff;
padding-top:30px;
min-height:70px:
border-bottom:#e8491d 3px solid;
}
header a{
color:#ffffff;
text-decoration:none;
text-transform:uppercase;
font-size:16px;
}
header u1{
margin:0;
padding:0;

}header l1{
float:left;
display:inline;
padding: 0 20px 0px;
}
header #branding{
float:left;
}
header #branding h1{
margin:0;}
header nav{
float:right;
margin-top:10px
}
header .highlight, header .current a{
color:#e8491d
font-weight:bold;
}
header a:hover{
color:#cccccc;
font-weight:bold;
}/*showcase*/
#showcase{
min-height:400px;
background:url("../img/showcase.jpg") no-repeat 0-400px;
text-align:center;
color:#ffffff;
}
#showcase h1{
margin-top:100px;
font-size:55px:
margin-bottom:10px;
}

#showcase p{
font-size:20px;
}
#newsletter{
padding:15pc;
color:#ffffff
background:#15424a
}
#newsletter h1
float:left;

#newsletter form
float:right;
margin-top:15px;
}
#newsletter input [type="mail"]{
padding:4px;
height:25px;
width:250px;
}
/*boxes*/
#boxes{
margin-top:20px;
}
#boxes .box{
float:left;
text-align: center;
width:30%
padding:10px;
}
#boxes .box img{
width:90px;
}
/*Sidebar*/
aside#sidebar{
float:right;
width:30%
margin-top:10px;
}
/*main-col */
artical#main-col{
float:left;
width:65%;
}
footer
padding:20px
margin-top:20px
color:#ffffff;
background-color:#e8491d;
text-align: center;
}
}

**Comment by Shawn58** [comment]
![image](https://cloud.githubusercontent.com/assets/27468422/25147512/c53e7fc0-2445-11e7-801b-3f9456907d94.png)

**Comment by redmunds** [comment]
You're still in the "Getting Started" folder. Use _File > Open Folder..._ to switch to the folder that contains your project files.

You can find more info about using Live Preview here:
* https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#live-preview
* https://github.com/adobe/brackets/wiki/Troubleshooting#livedev

**Comment by Shawn58** [comment]
Nah i think your talking about the index file thats not my project lol my projects is the working files the index file is the original file they provide when you download the program

**Comment by redmunds** [comment]
@Shawn58 Trust me on this one :)

**Comment by petetnt** [comment]
@Shawn58 The Live Preview depends on the Project folder like @redmunds says, so you need to open the folder `C:/users/shawn/Desktop/Final Website/coding` in the Project dropdown. (If it still doesn't work, you might also need to rename the file to `index.html` to it to work properly).

**Comment by Shawn58** [comment]
I think i tried to rename it to index.html once but got the same result but i'll try again

**Comment by petetnt** [comment]
Hi @Shawn58,

highlighted the Project dropdown as it's not entirely obvious for new users:

![image](https://cloud.githubusercontent.com/assets/7641760/25194723/02b26412-2544-11e7-844c-73a3af537bd6.png)

Clicking there open a dropdown, select `Open Folder` and navigate to the `C:/users/shawn/Desktop/Final Website/coding` folder. Live Preview should now work.

![image](https://cloud.githubusercontent.com/assets/7641760/25194762/25a20fd6-2544-11e7-9626-7c387a4e4094.png)

The working files (upper part of the left area) and the project tree (bottom part) are semi-related, but one can open files outside of the Project tree too (like you have). It might be something worth looking into if we could live preview any `.html` regardless of the folder.

**Comment by Shawn58** [comment]
man its still not working lol wtf its driving me crazy im working on a
really interesting project and this holding me up lol im going to just keep
asking man around the internet lol i'll try to post more on git hub too
until someone tells me what the issue is or i find out what the issue is
thanks man i'll post im at the library now lol its the only way i can get
internet access right now

**Comment by Shawn58** [comment]
man its really bothering me lol i need some answers is there anyone out there that can help

**Comment by petetnt** [comment]
Can you open the developer tools (Debug -> Show Developer Tools -> Console) and see if there are any errors after you press the live preview button ( ⚡️ )

**Comment by Shawn58** [comment]
lets see i'll try but if nothing works im going to suspect its my browsers my computer or something im thinking of moving all my important files to my second harddrive on my laptop and restoring lol this shit is driving me mad so im going to try that if nothing works

**Comment by Shawn58** [comment]
![image](https://cloud.githubusercontent.com/assets/27468422/25199622/70a221ae-2519-11e7-826d-bacc3bf74391.png)

**Comment by Shawn58** [comment]
![image](https://cloud.githubusercontent.com/assets/27468422/25199652/8492b76e-2519-11e7-9bfd-f2d7faaf630a.png)

**Comment by Shawn58** [comment]
ok it looks like some errors are there thinks for getting me this far now just have to find out what these errors mean lol

**Comment by Shawn58** [comment]
well im going to take a short break from brackets lmfao its driving me crazy lol but i wont give up

**Comment by petetnt** [comment]
The error in there seems to point out that you are still in the `Getting Started` folder, check out https://github.com/adobe/brackets/issues/13308#issuecomment-295371985 for instructions on how to open the correct folder 👍

**Comment by Shawn58** [comment]
oh well i wasnt there at first i just started moving shit around too much lmao because i litterally was trying everything but i'll look at what was said again in the previous comment

**Comment by Shawn58** [comment]
ok man im not going to lie i need some guidance here lol im tired and lazy right now and my head hurts and im new to this but how should i mive them exactly i once moved them to the get started folder on pirpose because i thought that would work lol so can i just move them back idk man what would you do i dont want screw anything up lol

**Comment by Shawn58** [comment]
i need some serious guidance and a break from this madness lol then i'll be ok just was pissed that i watched so many youtube videos and did so much work and is getting no where lol

**Comment by petetnt** [comment]
I understand your frustration. Oh now I see from the screenshots that your CSS file is actually called `rough draft website.css` instead of `style.css`? Rename that to `style.css`, and it should be in the `css` folder in your project to match what you have in the HTML file.

The steps needed (altogether) are:

1. You have the correct project open (C:/users/shawn/Desktop/Final Website/coding)
2. The project tree should look like this:
  ```
  css/
    style.css (renamed from `rough draft website.css`
  index.html (renamed from `rough draft website.html`)
  ```
3. Open the live preview and everything should work

**Comment by Shawn58** [comment]
![preview 1](https://cloud.githubusercontent.com/assets/27468422/25239816/27c36686-25bf-11e7-9f50-7b68b642551a.png)
![preview 2](https://cloud.githubusercontent.com/assets/27468422/25239821/2c9f62ae-25bf-11e7-9e5d-9bb43d0af3d9.png)
![preview part 3](https://cloud.githubusercontent.com/assets/27468422/25239830/32a59fec-25bf-11e7-8efe-5c20302ff3e1.png)
![preview part 4](https://cloud.githubusercontent.com/assets/27468422/25239836/36f6a938-25bf-11e7-9bdf-d7dd8e44ae7f.png)
![preview part 5](https://cloud.githubusercontent.com/assets/27468422/25239839/3a892b8e-25bf-11e7-817c-8ab04719dfcd.png)
![preview part 6](https://cloud.githubusercontent.com/assets/27468422/25239844/3dd93a4a-25bf-11e7-8d0e-daf8c34edb0a.png)
hey ok i have multiple screen shots of how my set up looks still have errors also still has me in the getting started folder
![image](https://cloud.githubusercontent.com/assets/27468422/25239912/74483752-25bf-11e7-8292-481b2a184896.png)
i also have changed the name many times in the link and its not helping. idk man 
this is the login page
