### ISSUE TITLE
Brackets is forcing to have libcurl3, and does not accept libcurl4

### ISSUE THREAD

**Issue by Qussayyon** [adobe/brackets#14171]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

I have Ubuntu 18.04, and the program `curl` recently requires `libcurl4`, when I tried to install `brackets` it asked me to remove `libcurl4` and install `libcurl3` so I had to remove curl in order to remove `libcurl4`.

### Steps to Reproduce

On Ubuntu with latest `curl` 7.58.0, if I try to install `brackets` I have to remove `curl`.

**Expected behavior:**
I thought `brackets` depends on `libcurl3` or more, so it should be happy with newer version of `libcurl` (i.e. version 4 `libcurl4`).

**Actual behavior:**
I had to choose between `brackets` 1.12 OR `curl`.
For time being I did choose to remove `curl` and have `brackets`

### Versions
OS: Ubuntu 18.04 (develpoment branch, will be released next month).

```
Release 1.12 build 1.12.0-17621 (release d3b783b99) 
build timestamp: Thu Feb 01 2018 12:36:24 GMT+0000
```

**Comment by Tinup-Ne** [comment]
Same issue on my Ubuntu 18.04. I have to remove Virtualbox to install Brackets.

**Comment by avidwriter** [comment]
Even worse on Ubuntu Server version it asks to remove package `ubuntu-server` when trying to install `libcurl3`

**Comment by alherrera42** [comment]
Same here. I can't even install Virtualbox on Ubuntu 18.04 because it asks for libcurl4, but I also need Brackets that much.

**Comment by elhoir** [comment]
I can confirm this issue too.

**Comment by rezamxy** [comment]
On Ubuntu 18.04 Bionic it asks to remove Virtualbox 5.2.10 and libcurl4.
```
Removing virtualbox-5.2 (5.2.10-122088~Ubuntu~bionic) ...
Removing libcurl4:amd64 (7.58.0-2ubuntu3) ..
```

**Comment by pmario** [comment]
That's a real deal-breaker. Is there any solution in sight?

**Comment by jsanta** [comment]
I just fixed it but had to rebuild the deb package. 

1. Download the .**_deb_** installer file
2. Inside the folder your downloaded the file run `dpkg-deb -R ./Brackets.Release.1.12.64-bit.deb Brackets `  
3. Edit file `Brackets/DEBIAN/control `and replace `libcurl3` with `libcurl4`
4. Rebuild .deb installer running `dpkg-deb -b Brackets Brackets-fixed.deb`
5. Install Brackets using the fixed installer running `sudo dpkg -i Brackets-fixed.deb `

At least the program opens. Don't know if there's anything broken though.

**Comment by Qussayyon** [comment]
@jsanta 
Thanks, it worked for me.

**Comment by jsanta** [comment]
@Qussayyon that's weird 'cause I installed a few extensions on my own installation of Brackets. I suspect mileage will vary depending on other factors (OS, other packages, any running firewalls, or else).
Sorry I can't give you any other hints.

**Comment by Qussayyon** [comment]
@jsanta,
Thanks, I figured it out, as I don't have any firewall or anything. also, I was unable to see files in files tree. It turns out that it needs to run as: `sudo brackets`
I thought  I was **not** the only who facing the issue.

**Comment by marc-portier** [comment]
trick suggested by @jsanta worked for me too
installing extra modules works
no sudo required

slight modification though: I replaced "libcurl3"  by the statement "libcurl3|libcurl4"
(seems less intrusive, and a possibility to have a Brackets deb that can work for more people accross the board (independt of them having either of those packages on board)

got the suggestion from reading this comment: https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294/comments/55

**Comment by Qussayyon** [comment]
@marc-portier 
gr8 trick, I was looking for a way to include either, but I didn't know how deb packages represent OR operation.

**Comment by koudeIka** [comment]
Confirmed on Debian Buster. Can't install Brackets because libcurl4 issue.
Trick suggested by @jsanta worked tough

**Comment by Skqnder** [comment]
For now, Brackets version provided in WebUpd8 PPA works with libcurl4. https://launchpad.net/~webupd8team/+archive/ubuntu/brackets

**Comment by lloony** [comment]
Confirmed and fix @jsanta worked 4 me too.

**Comment by Gabrock94** [comment]
Same issue on Linux Mint 19., asked me to remove R-cran and relative packages.
@jsanta solution worked for me, including installing extra modules.

**Comment by louistsaitszho** [comment]
Same issue on elementary 5.0 Juno, will try @jsanta solution tonight!

**Comment by disorder75** [comment]
@jsanta it works perfectly :-)

**Comment by RustyRaptor** [comment]
Question: Why don't we just fix the deb release to allow both versions of libcurl? This has been on for a while and it's really silly to have to repackage the deb yourself when it's such a simple fix.

**Comment by PlamenSh** [comment]
Perhaps a noobish observation but checking the code I cant find libcurl3 (or libcurl4) in it. Is this added during packaging? Im trying to make it work with both libcurl3 and libcurl4 as @marc-portier  and @RustyRaptor  suggested.

**Comment by RustyRaptor** [comment]
> Perhaps a noobish observation but checking the code I cant find libcurl3 (or libcurl4) in it. Is this added during packaging? Im trying to make it work with both libcurl3 and libcurl4 as @marc-portier and @RustyRaptor suggested.
> 
> **UPDATE**
> nvm I found it. The build instruction are here: https://github.com/adobe/brackets-shell/blob/master/installer/linux/debian/control

scroll up. It's added into the .deb file configuration. There are insructions above in the comments on how to unpack, edit, then repack the deb file to have it use whatever version of curl you need.

**Comment by PlamenSh** [comment]
@RustyRaptor yea the idea is to avoid this in future installs. Pull req with fix is sent for it.

**Comment by thunderamur** [comment]
Confirm issue.

**Comment by OmarAlbelbaisy** [comment]
> I just fixed it but had to rebuild the deb package.
> 
> 1. Download the .**_deb_** installer file
> 2. Inside the folder your downloaded the file run `dpkg-deb -R ./Brackets.Release.1.12.64-bit.deb Brackets `
> 3. Edit file `Brackets/DEBIAN/control `and replace `libcurl3` with `libcurl4`
> 4. Rebuild .deb installer running `dpkg-deb -b Brackets Brackets-fixed.deb`
> 5. Install Brackets using the fixed installer running `sudo dpkg -i Brackets-fixed.deb `
> 
> At least the program opens. Don't know if there's anything broken though.

It's installed but it's not working.

**Comment by OmarAlbelbaisy** [comment]
> I just fixed it but had to rebuild the deb package.
> 
> 1. Download the .**_deb_** installer file
> 2. Inside the folder your downloaded the file run `dpkg-deb -R ./Brackets.Release.1.12.64-bit.deb Brackets `
> 3. Edit file `Brackets/DEBIAN/control `and replace `libcurl3` with `libcurl4`
> 4. Rebuild .deb installer running `dpkg-deb -b Brackets Brackets-fixed.deb`
> 5. Install Brackets using the fixed installer running `sudo dpkg -i Brackets-fixed.deb `
> 
> At least the program opens. Don't know if there's anything broken though.

It's installed but it doesn't work!

**Comment by nilsjha** [comment]
I'm running Debian and libcurl3 is deprecated. It's a pity that this still is an issue!

**Comment by arf1372** [comment]
Now I'm using ubuntu 18.10 (cosmic) and same issue here.  
The official `.deb` file won't install on ubuntu cosmic and I going to install the snap version of brackets.

Here what I encounter:

```
$ sudo gdebi Brackets.Release.1.13.64-bit.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libcurl3
$ apt-cache policy libcurl3
libcurl3:
  Installed: (none)
  Candidate: (none)
  Version table:
$ apt-cache policy libcurl
N: Unable to locate package libcurl
$ apt-cache policy libcurl4
libcurl4:
  Installed: 7.61.0-1ubuntu2.3
  Candidate: 7.61.0-1ubuntu2.3
  Version table:
 *** 7.61.0-1ubuntu2.3 500
        500 http://archive.ubuntu.com/ubuntu cosmic-updates/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu cosmic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     7.61.0-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
$ brackets

Command 'brackets' not found, but can be installed with:

sudo snap install brackets
$ snap info brackets
name:      brackets
summary:   Brackets is a modern code editor for HTML, CSS and JavaScript.
publisher: Snapcrafters
contact:   https://github.com/snapcrafters/brackets/issues
license:   Proprietary
description: |
  Brackets is an open-source editor for web design and development
  built on top of web technologies such as HTML, CSS and JavaScript.
  The project was created and is maintained by Adobe, and is released
  under an MIT License.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
snap-id: NbcB8ZtSfH5bQIfyRynnlBeIIOyGurxD
channels:
  stable:    1.13 2019-02-04  (99) 103MB classic
  candidate: ↑                           
  beta:      1.13 2019-02-04  (99) 103MB classic
  edge:      1.13 2019-02-12 (100) 103MB classic
```

**Comment by shubhsnov** [comment]
> I just fixed it but had to rebuild the deb package.
> 
> 1. Download the .**_deb_** installer file
> 2. Inside the folder your downloaded the file run `dpkg-deb -R ./Brackets.Release.1.12.64-bit.deb Brackets `
> 3. Edit file `Brackets/DEBIAN/control `and replace `libcurl3` with `libcurl4`
> 4. Rebuild .deb installer running `dpkg-deb -b Brackets Brackets-fixed.deb`
> 5. Install Brackets using the fixed installer running `sudo dpkg -i Brackets-fixed.deb `
> 
> At least the program opens. Don't know if there's anything broken though.

Hey guys, you guys make the change mentioned above but instead of adding the dependency for libcurl4, just remove libcurl3 altogether. At the moment it seems that libcurl3 might even be a stale dependency, and won't have any impact if removed. I'm able to use Brackets with this change and without any issues on Ubuntu 18.04 LTS. 

Do let me know if there are any other issues that you encounter with this change

**Comment by marc-portier** [comment]
>... instead of adding the dependency for libcurl4, just remove libcurl3 altogether. At the moment it seems that libcurl3 might even be a stale dependency, ...

good point, however: "adding" in stead of "replacing" has (at least, had, one might observe) the benefit of (also) supporting those (stale) environments that just provide the v3 dependency

All of the above discussion is, of course, as time goes on with this issue unresolved, even while carrying an available pull request (thx @PlamenSh), pretty much: an archetypical moot-point. After all, the current position seems to be "We 've gone off the idea of support (for users or their platforms). It is overrated."

Sorry for my #h2gt2g inflicted irony there; I'll be lying in front of my bulldozer waiting for this case to get anyhwere. We'll see who rusts first!

**Comment by shubhsnov** [comment]
@marc-portier I think I might have misphrased but what I meant was "removing", not replacing or adding, because, **well Brackets just doesn't need it**. I've looked at @PlamenSh's PR (thanks for the fix). He's adding an OR dependency for both v3 and v4. We wouldn't want to do that if neither is needed which is how it seems at the moment. I'm still working on the issue, the above is just a workaround for those who wish to use Brackets and VirtualBox (or any other app which need v4) together. 

Thanks for the feedback. Do try out the workaround and let me know of any issues.

**Comment by marc-portier** [comment]
> well Brackets just doesn't need it

ah, didn't read it like that, totally makes sense, will try to find some time to test that out

**Comment by joshmckibbin** [comment]
This issue still exists in Brackets 1.14

**Comment by RustyRaptor** [comment]
This is really bad. It shouldn't be an issue just to include the fix in the release. What's going on?

**Comment by RyanNerd** [comment]
What?!? **This is a deal breaker**. I'm using PhpStorm and the built in web server went south. So I had used Brackets before in the past and figured I would just use Bracket's live reload to test my HTML, etc.
So I download and go to install the deb and it wants to **REMOVE** these (curl incompatibilities I can _kindasorta_ understand but this thing wants to remove cmake and ukuu?!?):
![image](https://user-images.githubusercontent.com/10543911/57914315-a05f6f00-784b-11e9-98b4-4a3a309bc038.png)

**Comment by shubhsnov** [comment]
@joshmckibbin @RustyRaptor @RyanNerd 
We are onto it. The dependencies listed for Brackets were decided by the dependencies that Chromium had. We're in the process of updating CEF (the Chromium-based shell we use) for Linux (https://github.com/adobe/brackets-shell/pull/666) to almost the latest version and then update the dependencies accordingly. Once that is done the dependencies will come up to date with Chrome 60+, which means that Brackets would install without any issues if Chrome does as well.

Since CEF was a big change we wanted to be sure and fix the issue at the root cause rather than just patching the dependency list.

Meanwhile please use this workaround to tackle the issue: https://github.com/adobe/brackets/issues/14786

**Comment by dutsov** [comment]
Version 1.14 and the problem with curl version is still persistent!

**Comment by MostHated** [comment]
I can't install either. How can this still be an issue after over a year?

**Comment by t1logy** [comment]
It is July 27 and I still can't install version 1.14 on Ubuntu 19.04, though I tried to remove `libcurl3`. WTF?

**Comment by k4kfh** [comment]
Yeah, I agree this is a little crazy. It's been over a year and it still
requires manual screwing with packages to install on one of the most
beginner-friendly and well known Linux distros. I'm not a contributor, and
I hate to sound whiny, because maybe it really is a difficult problem to
solve. But it certainly seems like this is not getting the priority it
deserves.

**Comment by RustyRaptor** [comment]
I hope this gets resolved soon.

**Comment by joshmckibbin** [comment]
I gave up on Brackets and decided to just switch to Visual Studio Code

**Comment by t1logy** [comment]
@joshmckibbin, +++

**Comment by MostHated** [comment]
I just got it from the flatpack software center and it installed just fine that way.

**Comment by k4kfh** [comment]
The thing that keeps me on Brackets is the live preview. It's second to none. So far I haven't found a plugin for any other editor that is as good. But I agree, I pretty much only use Brackets for web development now because it's not as well suited for "traditional" programming, and because now it's a PITA to install...lol

**Comment by t1logy** [comment]
@k4kfh, I started using VS Code and I really miss live preview(((

**Comment by RustyRaptor** [comment]
> @k4kfh, I started using VS Code and I really miss live preview(((

VSCode has a live-preview server plugin that works similar to the one in Brackets. Sadly doesn't scroll to the place when you click an element at least last time I checked.

**Comment by ElSaico** [comment]
Another possible (and cleaner?) workaround is this PPA that replaces libcurl4 with a version that explicitly provides libcurl3 - and thus works for other packages stuck on it as well.

https://launchpad.net/~xapienz/+archive/ubuntu/curl34

**Comment by its-thomas** [comment]
May I suggest the following workaround: Installing Brackets as a snap via [Snapcraft.io](https://snapcraft.io/brackets). Works for me in Lubuntu 18.04.

**Comment by Qussayyon** [comment]
> Another possible (and cleaner?) workaround is this PPA that replaces libcurl4 with a version that explicitly provides libcurl3 - and thus works for other packages stuck on it as well.
> 
> https://launchpad.net/~xapienz/+archive/ubuntu/curl34

There is a reason why Ubuntu moved from `libcurl3` to `libcurl4`, it's the security!

**Comment by amankakar** [comment]
### ERROR
i had same issue while installing curl.
`sudo apt-get install curl`
** curl : Depends: libcurl4 (= 7.58.0-2ubuntu3.8ppa2) but it is not going to be installed
**
when i try to install curl4 it give me error:
`sudo apt-get install libcurl4 curl`
** mongodb-org-server : Depends: libcurl3 (>= 7.16.2) but it is not going to be installed
**
but i had already curl3 with latest version.

### Solution
i have  Ubuntu 18.04.2 LTS codname bionic
i execute following commands:
first i install curl4 required version:
`sudo apt-get install libcurl4=7.58.0-2ubuntu3.8ppa2
`
above command will remove error of culr3 and curl4
then i execute command install curl 
`sudo apt-get install curl`
curl installed successfully

**Comment by Ray6464** [comment]
Same issue here, I just installed Brackets (and loving it) on Ubuntu 18.04 LTS using the ".deb" package and it is working great! but Ubuntu is giving be an error/notification of unmet dependencies.

When I run "sudo apt upgrade" I get the following error:
---
The following packages have unmet dependencies:
 brackets : Depends: libcurl3 but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
---

**Comment by Ray6464** [comment]
There is a duplicate issue #14667

**Comment by PeterNdomano** [comment]
I used @jsanta 's solution on Parrot OS and Brackets was installed but it never opens or start

**Comment by i0x71** [comment]
> I just fixed it but had to rebuild the deb package.
> 
>     1. Download the .**_deb_** installer file
> 
>     2. Inside the folder your downloaded the file run `dpkg-deb -R ./Brackets.Release.1.12.64-bit.deb Brackets `
> 
>     3. Edit file `Brackets/DEBIAN/control `and replace `libcurl3` with `libcurl4`
> 
>     4. Rebuild .deb installer running `dpkg-deb -b Brackets Brackets-fixed.deb`
> 
>     5. Install Brackets using the fixed installer running `sudo dpkg -i Brackets-fixed.deb `
> 
> 
> At least the program opens. Don't know if there's anything broken though.

Its been over a year and people still have to google around for this solution, meanwhile 1.14.1 just got released. Why couldn't this have been already fixed ?

**Comment by rodrigofbm** [comment]
2020 overthere and this still here. They don't give a shi** for us. Moving for VS Code...

**Comment by LDLanagan** [comment]
> For now, Brackets version provided in WebUpd8 PPA works with libcurl4. https://launchpad.net/~webupd8team/+archive/ubuntu/brackets

Can confirm it works on Bionic and it's my favorite editor ever, so loving this poster more than ice cream rn. <3 <3

**Comment by eaxode** [comment]
Not fixed by now :/
Xubuntu 20.04

**Comment by RustyRaptor** [comment]
Been using VSCode for the past 2 years. I'm still reminded every month by Github that this is still an issue. Tragic.

**Comment by 440music** [comment]
August 31, 2020 4:51PM Chicago, IL USA

I've been looking for an answer to file tree not showing up and none of the solutions I've found haven't worked. 2.5 years from the first post and this issue is still an issue. I've wasted more time than I can count any more and I'm getting frustrated, I also tried to install an extension and the extension manager just spins and will not connect, I waited 15 minutes and nothing. 

Can we still trust Brackets to be a valuable tool? Not me

I was using Brackets on Ubuntu 18.04 and had no issues and after the upgrade to Ubuntu 20.04 I lost the file tree

FIX IT NOW!

**Comment by M-DVD** [comment]
> I used @jsanta 's solution on Parrot OS and Brackets was installed but it never opens or start

Same here in Debian 10.

**Comment by AleBG** [comment]
> Same issue on Linux Mint 19., asked me to remove R-cran and relative packages.
> @jsanta solution worked for me, including installing extra modules.

Same for me, 2 years later. I wanted to give Brackets a try since I'm learning some web development, but I need R so there's no way I'm installing Brackets. And I'm not an expert, but isn't curl like a very basic Bash program? (in the sense that it sounds like a bad idea to remove it)

**Comment by sk8807307** [comment]
thanks it works on MX_LINUX petito feo 19

**Comment by yonderbread** [comment]
> I just fixed it but had to rebuild the deb package.
> 
>     1. Download the .**_deb_** installer file
> 
>     2. Inside the folder your downloaded the file run `dpkg-deb -R ./Brackets.Release.1.12.64-bit.deb Brackets `
> 
>     3. Edit file `Brackets/DEBIAN/control `and replace `libcurl3` with `libcurl4`
> 
>     4. Rebuild .deb installer running `dpkg-deb -b Brackets Brackets-fixed.deb`
> 
>     5. Install Brackets using the fixed installer running `sudo dpkg -i Brackets-fixed.deb `
> 
> 
> At least the program opens. Don't know if there's anything broken though.

Tysm this worked

**Comment by xekon** [comment]
I give up, this worked good for me:

`sudo apt install kate`

**Comment by xekon** [comment]
Does anyone know if there are any Major forks of Brackets? ones with more active development?

**Comment by yonderbread** [comment]
> Does anyone know if there are any Major forks of Brackets? ones with more active development?

i wasnt able to find any, but if youre looking for a good editor just use Notepad++

**Comment by L-S-M** [comment]
How is this still an issue in Dec 2020?

**Comment by eaxode** [comment]
Adobe Inc. is increasingly fighting against insignificance. Therefore it is not so tempting to try to get a contract with them.
You can see that very well on https://github.com/adobe/brackets/graphs/contributors

I'm afraid you'll have to fix it yourself or switch to a software with active development. Keeping them up is easy.
