### ISSUE TITLE
Error Reading Preferences - not valid JSON

### ISSUE THREAD

**Issue by milkymeda** [adobe/brackets#14792]
I'm trying to change the PHP "executablePath" in order to get PHP Tooling support and I got this error:

>  Your preferences file is not valid JSON. Please fix the format.

Here is my brackets.json:

```
 {
    "brackets-eslint.gutterMarks": true,
    "brackets-eslint.useLocalESLint": false,
    "fonts.fontSize": "13px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "themes.theme": "monokai-plus-theme",
    "livedev.multibrowser": false,
    "useTabChar": false,
    "themes.themeScrollbars": true,
    "extensions.sort": "downloadCount"
    "php": {
		// Default: true
		"enablePhpTooling": true,

		// Default: php
		"executablePath": "C:\xampp\php\php.exe",

		// Default: 4095M
		"memoryLimit": "4095M",

		// Default: false
		"validateOnType": "true"
	},
}
```

I've tried different things like adding only this line, with/without the comma etc.

`"executablePath": "C:\xampp\php\php.exe",`

But none of them worked. What could be the problem?

Thank you.

**Comment by shubhsnov** [comment]
You can't have comments in brackets.json. Removing them should fix it.
You can refer to this in case you have any doubts. https://github.com/adobe/brackets/issues/14783
Let us know if there are still any issues you faith.

**Comment by milkymeda** [comment]
Unfortunately, it did not work. Here is the current state of brackets.json:

```
{
    "brackets-eslint.gutterMarks": true,
    "brackets-eslint.useLocalESLint": false,
    "fonts.fontSize": "13px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "themes.theme": "monokai-plus-theme",
    "livedev.multibrowser": false,
    "useTabChar": false,
    "themes.themeScrollbars": true,
    "extensions.sort": "downloadCount"
    "php": {
        "enablePhpTooling": true,
        "executablePath": "C:\xampp\php\php.exe",
        "memoryLimit": "4095M",
        "validateOnType": "false"
    }
}
```

**Comment by sprintr** [comment]
@milkymeda You have to put `executablePath` like such `"C:\\xampp\\php\\php.exe"` to escape backspace.

**Comment by milkymeda** [comment]
That worked! Thanks a lot!

```
{
    "brackets-eslint.gutterMarks": true,
    "brackets-eslint.useLocalESLint": false,
    "fonts.fontSize": "13px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "themes.theme": "monokai-plus-theme",
    "livedev.multibrowser": false,
    "useTabChar": false,
    "themes.themeScrollbars": true,
    "extensions.sort": "downloadCount",
    "php": {
    "executablePath": "C:\\xampp\\php\\php.exe",
    "validateOnType": "true"
    }
}
```

**Comment by marshalnosa** [comment]
> That worked! Thanks a lot!
> 
> ```
> {
>     "brackets-eslint.gutterMarks": true,
>     "brackets-eslint.useLocalESLint": false,
>     "fonts.fontSize": "13px",
>     "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
>     "themes.theme": "monokai-plus-theme",
>     "livedev.multibrowser": false,
>     "useTabChar": false,
>     "themes.themeScrollbars": true,
>     "extensions.sort": "downloadCount",
>     "php": {
>     "executablePath": "C:\\xampp\\php\\php.exe",
>     "validateOnType": "true"
>     }
> }
> ```

I am having same issue here and I added this code but my Brackets still having the issue of resetting itself after lunching. 

I still get the default theme and font size whenever I restart.

Secondly, it still takes me to this JSON error page instead of my previous project.

Any help on how to solve this?

Thanks

![image](https://user-images.githubusercontent.com/51928781/68527315-6beddc80-02dd-11ea-8f03-bdadc66f6c18.png)

**Comment by sprintr** [comment]
@marshalnosa Have you used valid JSON?

**Comment by marshalnosa** [comment]
> @marshalnosa Have you used valid JSON? Can you share your `preferences.json`?

@sprintr, I can't find the preference.json file here. 

How do I go about that?

**Comment by saohlsen** [comment]
Hi, 
Getting "error reading preferences" - "Your preferences file is not valid JSON."

Anyone know what is wrong with it ?

{
    "brackets-eslint.gutterMarks": true,
    "brackets-eslint.useLocalESLint": false,
    "fonts.fontSize": "14px",
    "fonts.fontFamily": "hack, 'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "themes.theme": "os-x-style-flat-dark-theme",
    "useTabChar": true,
    "tabSize": 3,
    "linting.collapsed": true,
    "linting.ESLint.collapsed": false,
    "linting.JSLint.collapsed": true,
    "livedev.multibrowser": true,
}

**Comment by redmunds** [comment]
@saohlsen I think you need to remove the trailing comma from the last line:
```
"livedev.multibrowser": true
```

**Comment by saohlsen** [comment]
@redmunds @ oh boy! Thank you, it works.

**Comment by pol1up** [comment]
I have a similar problem... 

    "brackets-eslint.gutterMarks":` true,
    "brackets-eslint.useLocalESLint": false,
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "themes.theme": "monokai-darkness-reborn",

I am still getting an error

**Comment by sk-ismail** [comment]
There is an error in first line... 
"brackets-eslint.gutterMarks":` true,
you have to remove that single invited comma in front of true

**Comment by justyb00** [comment]
```
I have a similar problem...
{
    "brackets-eslint.gutterMarks": true,
    "brackets-eslint.useLocalESLint": false,
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "linting.ESLint.collapsed": false,
    "linting.collapsed": true,
    "externalApplications": {
        "jpg": "D:\\Apps\\IrfanView\\i_view64.exe",
        "jpeg": "D:\\Apps\\IrfanView\\i_view64.exe",
        "png": "D:\\Apps\\IrfanView\\i_view64.exe",
        "svg": "C:\\Program Files\\Internet Explorer\\iexplore.exe",
        "psd": "D:\\Apps\\IrfanView\\i_view64.exe",
        "php": {
        "enablePhpTooling": true,
        "executablePath": "C:\\Apps\\scoped_dir3768_943626505\\OpenServer\\modules\\php\\PHP_7.4\\php.exe",
        "memoryLimit": "4095M",
        "validateOnType": "false"
        }
    }
}

```

but PHP runtime doesn't work.
![image](https://user-images.githubusercontent.com/69864983/110860293-a3074000-82cd-11eb-9d40-6ffcb236b356.png)
