### ISSUE TITLE
Mac 10.9: Brackets Helper process erroneously shown as "Not Responding" in Activity Monitor

### ISSUE THREAD

**Issue by dalcala** [adobe/brackets#5794]
Description:
Mac 10.9: Brackets Helper process Not Responding 15-20 seconds after launch in Activity Monitor.  Shows up in red text in Activity Monitor.  The same thing happens with Google Chrome on Mac 10.9, so this is a tracking bug.  According to Peter Flynn, it's the GPU helper.  We checked the Chrome process ID that was not responding > opened Chrome's task manager (hamburger icon > Tools > Task Manager) > mapped not responding process ID from Activity Monitor to process ID in Chrome Task Manager > GPU Process.  Here is the Chromium bug for this issue:

Issue 304860:	Mavericks: Helper processes shown in Activity Monitor as "Not Responding"
https://code.google.com/p/chromium/issues/detail?id=304860

![chrome-not-responding](https://f.cloud.github.com/assets/1512954/1450130/7a8cf82c-4275-11e3-8427-9b0a68de8f7a.png)

![chrome-task-manager](https://f.cloud.github.com/assets/1512954/1450131/7e97193e-4275-11e3-972f-60c1034686d7.png)

Repro on Mac 10.9 using Brackets Sprint 33 10188 GM, Sprint 32 9791 GM, Sprint 31 9569 GM.  UTR on Mac 10.8 using BK Sprint 33 GM 10188.  

Repro steps:
1.  Install Brackets on Mac 10.9.
2.  Launch Activity Monitor.
3.  Launch Brackets.
4.  Watch Activity Monitor for ~15-20 seconds.

Actual results:
Activity Monitor says Brackets Helper process is not responding.  

![bk-helper-not-responding](https://f.cloud.github.com/assets/1512954/1450129/6a48b8a2-4275-11e3-8127-62881b745684.png)

Expected results:
Brackets Helper is responding.

Workaround:
None.  Everything seems to be working fine, so it appears this is a false positive.  Comment from Chromium bug: "This is an issue with how Activity Monitor determines responsiveness – these processes are running perfectly fine. (We changed chrome to work around that Activity Monitor issue, and the fix will reach you eventually, depending on which channel you use, how far we merge this, etc.)"

**Comment by ElegantScripting** [comment]
From what I can see, this isn't related to chrome. I don't use Chrome, only Safari.

Brackets Helper on my Mac isn't responding as well, on fresh restart, without the use of live preview.

**Comment by prksingh** [comment]
This bug is about brackets helper 'erroneously' appearing unresponsive in Activity monitor. 
The application should not be affected by this. Do you mean the same?

Also which version of brackets are you using? I notice from the comments above that the issue may have been fixed in the chromium build we integrated some time back. Are you seeing this in Brackets 1.2?

**Comment by peterflynn** [comment]
@prksingh Good catch!  It does appear fixed now on Mac, so let's close it.

@ElegantScripting If you're seeing slow performance when using Live Preview, that's a different issue. Could you file a new bug with more details? (E.g. does it happen with the simple Getting Started project that comes with Brackets too, or only with your own projects?)

**Comment by ElegantScripting** [comment]
- No live preview
- Extensions disabled
- Restarted brackets
- Using latest version

![screen shot 2015-04-08 at 5 18 30 pm](https://cloud.githubusercontent.com/assets/5307412/7055717/b6479cc4-de13-11e4-8d3d-4e955a8c96d9.png)

**Comment by peterflynn** [comment]
Hmm, so apparently looks like the Chrome bug regressed on Yosemite: https://code.google.com/p/chromium/issues/detail?id=397642.

They did land a fix on the Chrome 39 2171 branch shortly before we started out upgrade  to CEF 2171, but I'm guessing we just narrowly missed the boat on picking up that fix. (If I'm reading the version numbers right, [we need 2171.50](https://chromium.googlesource.com/chromium/src/+/43b5d400d15fb8e1bfea129c42df7810d5a5e8f9/chrome/VERSION) and we currently have 2171.36).

Updating the bug title and reopening.

**Comment by schroef** [comment]
Im seeing this on OSX 10.10.2 its a old mac and ive got latest bracket 1.11 
What i find weird is that in [post](https://github.com/adobe/brackets/issues/5794#issuecomment-88203785), while its was 2 yr ago, he talk abouts brackets 1.2???

Reloading without extension still shows the issue. Beeing that my system is old it doesnt really slow down unless i open a couple documents and do some other heavy stuff. Its a core 2 duo 2.4 with 4g Ram.

I never really bothered about this cause normally i work on a macbook pro 16g mid 2015.
